import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const N=6;
const key=(r,c)=>`${r},${c}`;
const dirs=[[1,1],[1,-1],[-1,1],[-1,-1]];
const inBounds=(r,c)=>r>=0&&r<N&&c>=0&&c<N;
function movesFor(board,p){const out=[];for(const[dr,dc]of dirs){const r=p.r+dr,c=p.c+dc;if(inBounds(r,c)&&!board[key(r,c)])out.push({r,c,capture:null});const mr=p.r+dr,mc=p.c+dc,jr=p.r+2*dr,jc=p.c+2*dc;if(inBounds(jr,jc)&&board[key(mr,mc)]&&board[key(mr,mc)].player!==p.player&&!board[key(jr,jc)])out.push({r:jr,c:jc,capture:key(mr,mc)});}return out}
function App(){
 const[phase,setPhase]=useState('setup'),[setupPlayer,setSetupPlayer]=useState(1),[placements,setPlacements]=useState({1:[],2:[]}),[board,setBoard]=useState({}),[turn,setTurn]=useState(1),[selected,setSelected]=useState(null),[scores,setScores]=useState({1:0,2:0}),[winner,setWinner]=useState(null),[round,setRound]=useState(1),[message,setMessage]=useState('Player 1: choose 3 starting squares.');
 const legal=useMemo(()=>selected?movesFor(board,selected):[],[board,selected]), legalKeys=new Set(legal.map(x=>key(x.r,x.c)));
 function place(r,c){if(phase!=='setup'||placements[setupPlayer].length>=3||[...placements[1],...placements[2]].some(p=>p[0]===r&&p[1]===c))return;const next=[...placements[setupPlayer],[r,c]];setPlacements({...placements,[setupPlayer]:next});if(next.length===3){if(setupPlayer===1){setSetupPlayer(2);setMessage('Player 2: choose 3 starting squares.')}else setMessage('Both players are placed. Start the round.')}}
 function start(){const all=[...placements[1].map((x,i)=>({id:`1-${i}`,player:1,r:x[0],c:x[1]})),...placements[2].map((x,i)=>({id:`2-${i}`,player:2,r:x[0],c:x[1]}))];setBoard(Object.fromEntries(all.map(p=>[key(p.r,p.c),p])));setPhase('play');setTurn(1);setSelected(null);setMessage('Player 1 turn. Select a piece.')}
 function select(r,c){const p=board[key(r,c)];if(p?.player===turn){setSelected(p);setMessage(`Player ${turn}: choose a diagonal move or jump.`)}else if(selected&&legalKeys.has(key(r,c)))move(r,c)}
 function move(r,c){const dest=legal.find(x=>x.r===r&&x.c===c);if(!dest)return;const next={...board},from=key(selected.r,selected.c),to=key(r,c);delete next[from];if(dest.capture)delete next[dest.capture];const scored=(selected.player===1&&r===N-1)||(selected.player===2&&r===0);const nextScores={...scores,[turn]:scores[turn]+(scored?1:0)};if(!scored)next[to]={...selected,r,c};setBoard(next);setScores(nextScores);setSelected(null);if(nextScores[turn]===3){setWinner(turn);setPhase('over');setMessage(`Player ${turn} got all 3 pieces across.`);return}const other=turn===1?2:1;const any=Object.values(next).some(p=>movesFor(next,p).length>0);if(!any){const w=nextScores[1]===nextScores[2]?0:(nextScores[1]>nextScores[2]?1:2);setWinner(w);setPhase('over');setMessage(w?`Player ${w} wins on points.`:'Round ends in a tie.');return}setTurn(other);setMessage(`Player ${other} turn. Select a piece.`)}
 function reset(){setPhase('setup');setSetupPlayer(1);setPlacements({1:[],2:[]});setBoard({});setTurn(1);setSelected(null);setScores({1:0,2:0});setWinner(null);setRound(round+1);setMessage('Player 1: choose 3 starting squares.')}
 return <main><section className="top"><div><div className="eyebrow">ROUND {round}</div><h1>HIDDEN CHECKERS</h1><p>Place in secret. Reveal the board. Race to the far side.</p></div><div className="scores"><div><span className="dot p1"/>PLAYER 1 <b>{scores[1]}</b></div><div><span className="dot p2"/>PLAYER 2 <b>{scores[2]}</b></div></div></section><section className="game"><div className="status"><span className={phase==='play'?'live':''}/>{message}</div><div className="board">{Array.from({length:N},(_,r)=>Array.from({length:N},(_,c)=>{const p=board[key(r,c)],placed=[...placements[1],...placements[2]].some(x=>x[0]===r&&x[1]===c),target=phase==='play'&&legalKeys.has(key(r,c));return <button key={key(r,c)} className={`cell ${(r+c)%2?'dark':'light'} ${target?'target':''} ${phase==='setup'&&!placed?'setup':''}`} onClick={()=>phase==='setup'?place(r,c):select(r,c)}>{p&&<span className={`piece p${p.player} ${selected?.id===p.id?'selected':''}`}>{p.player}</span>}{phase==='setup'&&placed&&<span className="hiddenMark">●</span>}</button>}))}</div><div className="legend"><span><i className="sample p1"/>Player 1</span><span><i className="sample p2"/>Player 2</span><span>Diagonal step or jump</span></div>{phase==='setup'&&placements[1].length===3&&placements[2].length===3&&<button className="primary" onClick={start}>REVEAL BOARD & START</button>}{phase==='over'&&<div className="end"><strong>{winner===0?'TIE GAME':`PLAYER ${winner} WINS`}</strong><button className="primary" onClick={reset}>NEW ROUND</button></div>}</section><section className="rules"><div><b>SETUP</b><span>Each player secretly places 3 pieces.</span></div><div><b>MOVE</b><span>Move one square diagonally or jump an opposing piece.</span></div><div><b>SCORE</b><span>Reach the opposite edge to score and remove your piece.</span></div></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
